# notify-done.config.ps1 - 默认配置
# Default configuration for notify-done system.
#
# 不要直接修改此文件！请创建 notify-done.config.user.ps1 只写你想覆盖的项。
# Do NOT edit this file directly! Create notify-done.config.user.ps1 with only the values you want to override.
#
# 示例 / Example  notify-done.config.user.ps1:
#   $Config.DefaultVolume = 60
#   $Config.Popup.AccentColor = @(255, 128, 0)
#

if (-not $Config) {
    $Config = @{}
}

# ============================================================
# General / 通用
# ============================================================
$Config.DefaultMessage     = "任务完成！"       # 默认提醒消息 / Default reminder message
$Config.DefaultVolume      = 100                # 默认音量 0-100 / Default volume
$Config.TTS                = @{
    Rate           = 0                          # 语速 -10~10 / Speech rate
    SinglePrefix   = "AI工作完成。"              # 单语模式前缀 / Prefix for single-language TTS
}

# ============================================================
# Popup / 浮窗
# ============================================================
$Config.Popup = @{
    Width          = 440
    Height         = 340
    CornerRadius   = 14
    Opacity        = 0.98
    FadeStep       = 0.05                       # 淡入步长 / Fade-in step

    # 字体 / Fonts
    FontFamily     = "Microsoft YaHei UI"
    FontFamilyMono = "Segoe UI"
    TitleFontSize  = 11
    MsgFontSize    = 10
    HintFontSize   = 9
    BtnFontSize    = 9

    # 颜色 (R, G, B) / Colors
    BgColor           = @(18, 20, 28)
    TitleColor        = @(26, 29, 39)
    AccentColor       = @(66, 153, 255)
    AccentSoft        = @(34, 78, 132)
    BorderColor       = @(58, 65, 82)
    TextPrimary       = @(242, 245, 250)
    TextSecondary     = @(162, 170, 184)
    BtnBg             = @(42, 46, 58)
    BtnHover          = @(56, 62, 76)
    BtnPrimaryBg      = @(38, 115, 220)
    BtnPrimaryHover   = @(55, 140, 250)
    SeparatorColor    = @(44, 50, 64)
    GlowTopColor      = @(48, 86, 138)
    CopiedBtnColor    = @(42, 146, 78)
}

# ============================================================
# Tone / 提示音 (notify-tone-boot.ps1)
# ============================================================
$Config.Tone = @{
    Duration       = 4.5                        # 音效时长秒 / Duration in seconds
    SampleRate     = 44100
}

# ============================================================
# Alert Tone / 警报音 (notify-tone.ps1)
# ============================================================
$Config.AlertTone = @{
    Duration       = 10.0                       # 警报音时长秒 / Alert duration in seconds
    SampleRate     = 44100
}
